### ISSUE TITLE
Deprecation warning about "url"

### ISSUE THREAD

**Issue by uprise10** [glebm/sass-rewrite-url#2]
I'm getting this warning now while compiling: 
`DEPRECATION WARNING on line 5 of _source/css/main/plugins/_rewrite-url.scss:
Naming a function "url" is disallowed and will be an error in future versions of Sass.
This name conflicts with an existing CSS function with special parse rules.`

Sounds like this solution cannot be used anymore in the future (other than renaming the function)?

**Comment by glebm** [comment]
That's right. I've added a warning to the top of the Readme. Consider postprocessing alternatives such as https://github.com/postcss/postcss-url.
